library(compiler)
compilePKGS(T)

#### PATCH NOTE ####
## 2017-02-12: Version 0.2 environment
## 2017-02-05: Version 0.1


# #### FILE TYPE ####
# FILE.TYPES <- c('MT4-EA' = 'Strategy Tester:',
#                'MT4-TRADE' = 'Statement:',
#                'MT5-EA' = 'Strategy Tester Report',
#                'MT5-TRADE' = 'Trade History Report',
#                'MT4M-CLOSED' = 'Closed Trades Report',
#                'MT4M-RAW' = 'Raw Report')

#### PARALLEL THRESHOLD ####
PARALLEL.THRESHOLD.READ.FILES <- 200
PARALLEL.THRESHOLD.GENERATE.TICKETS <- 6
PARALLEL.THRESHOLD.DB.SYMBOLS <- 6

#### SYMBOLS SETTING ####
SYMBOLS.SETTING <-
  data.table(
    SYMBOL = c('AUDCAD', 'AUDCHF', 'AUDJPY', 'AUDNZD', 'AUDUSD', 'CADCHF', 'CADJPY', 'CHFJPY', 'EURAUD', 'EURCAD',
               'EURCHF', 'EURGBP', 'EURJPY', 'EURNZD', 'EURUSD', 'GBPAUD', 'GBPCAD', 'GBPCHF', 'GBPJPY', 'GBPNZD',
               'GBPUSD', 'NZDCAD', 'NZDCHF', 'NZDJPY', 'NZDUSD', 'USDCAD', 'USDCHF', 'USDJPY', 'XAGUSD', 'XAUUSD'),
    SPREAD = c(40,40,40,40,20,40,40,40,40,40,40,40,40,40,20,40,20,40,40,40,20,40,40,40,20,20,20,40,50,500),
    DIGITS = c(5,5,3,5,5,5,3,3,5,5,5,5,3,5,5,5,5,5,3,5,5,5,5,3,5,5,5,3,3,2),
    CONTRACT.SIZE = c(rep(100000, 28), 1000, 100)
  ) %>%
  extract(j = TICKVALUE.POINT := CONTRACT.SIZE * 10 ^ -DIGITS) %>%
  setkey(SYMBOL)

SUPPORT.SYMBOLS <- SYMBOLS.SETTING[, SYMBOL]

#### TIMEFRAMES ####
TIMEFRAMES <- c('M1', 'M5', 'M15', 'M30', 'H1', 'H4', 'D1', 'W1', 'MN')
TIMEFRAME.INTERVAL <-
  c(60, 300, 900, 1800, 3600, 14400, 86400, 43200, 1728000) %>%
  set_names(TIMEFRAMES)
TIMEFRAME.TICKVALUE <- 'M1'
TIMEFRAME.REPORT <- 'H1'

#### DEFAULT LEVERAGE ####
DEFAULT.LEVERAGE <- 100

#### DEFAULT CURRENCY ####
DEFAULT.CURRENCY <- 'USD'

#### DEFAULT INIT.MONEY ####
DEFAULT.INIT.MONEY <- 10000

#### REPORT CONTENT ####
CONTENT.PHASE1 <- c('INFOS', 'HTML.PARSE', 'PATH')
CONTENT.PHASE2 <- c('CURRENCY', 'LEVERAGE', 'TICKETS.RAW', 'ITEM.SYMBOL.MAPPING', 'SUPPORTED.ITEM',
                    'UNSUPPORTED.ITEM', 'TICKETS.SUPPORTED', 'TICKETS.EDITING')
CONTENT.PHASE3 <- c('TICKETS.EDITED', 'TICKETS.MONEY', 'PERIOD', 'PRICE', 'TIMESERIE.TICKETS',
                    'TIMESERIE.SYMBOLS', 'TIMESERIE.ACCOUNT', 'SYMBOLS.PROFIT_VOLUME')